"""modify user_model

Revision ID: 9651c125b134
Revises: d91f36bdd921
Create Date: 2022-05-17 12:38:41.868435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9651c125b134'
down_revision = 'd91f36bdd921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time', sa.DateTime(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('user', 'time')
    # ### end Alembic commands ###
