"""two modify user_model

Revision ID: d6d141cb435a
Revises: 9651c125b134
Create Date: 2022-05-17 12:53:51.191180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6d141cb435a'
down_revision = '9651c125b134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
